train_data_dir: data/Training_Corpora/SemCor
val_data_dir: data/Evaluation_Datasets/semeval2007
model_name: distilbert-base-uncased
output_dir: output/semeval2007
num_sense: 5
max_seq_len: 128
batch_size: 1
lr: 0.00001
weight_decay: 0.01
epochs: 3
logging_step: 10
precision: fp16
warmup_ratio: 0.1
grad_clip: 1.0
pos: ALL
device: cpu
seed: 1234
workers: 1
report_to: none
architecture: span_extraction
