train_data_dir: data/Training_Corpora/SemCor
val_data_dir: data/Evaluation_Datasets/semeval2007
model_name: distilbert-base-uncased
output_dir: output
num_sense: 5
max_seq_len: 128
batch_size: 16
lr: 0.00001
weight_decay: 0.01
epochs: 3
logging_step: 2000
precision: fp16
warmup_ratio: 0.1
grad_clip: 1.0
pos: ALL
device: cuda
seed: 42
workers: 1
report_to: wandb
architecture: span
do_predict: true
